### ISSUE TITLE
Skinning Engine and General Developer Questions

### ISSUE THREAD

**Issue by antonic901** [brentdc-nz/XBMC-360#14]
I'm opening this issue for general discussion about XBMC-360 development. These issue is meant for developers and not for general help :) So I will start with my questions.

1. **Skinning engine / GUILIB** - If I understand correctly your main task is to finish all GUI controls so skins from XBMC4Xbox can be used. That will make them compatible with XBMC-360 out-of-the box, am I right? I've build app from Development branch, but I couldn't get focus on control, even though I set inside `<defaultcontrol></defaultcontrol>` number "4" which was ID of my button control that activates Settings window (Settings.xml). So I was wondering is that some bug? Maybe better options would be to first port whole GUILIB from XBMC4Xbox and after that start adding new features from Kodi.
2. **Video playback / DVDPlayer/FFMpeg** - I've tried a lof of different video files and general rule is that 720p/H.263 (know as DiVX and XviD) are playing very well, but video quality of this videos is bad at bigger screens. Also Original Xbox is also capable of playing this videos so there is no suprise they work on 360. But 720p/1080p H.264 (known as WEB-DL, YTS, YIFY and similar releases) are no way to go for 360. 1080p H.264 wont even start, and 720p H.264 are stuttering as hell (unwachable, frame skipping, 10-12FPS). Taking in considiration how much power 360 has against Original Xbox it would be really a shame if we can't get working at least 1080p H.264/265 video files. I don't know is this something related to old version of FFmpeg but I hope that there is fix for this.
3. Is there any official docs that explains how to debbug with 360 inside VS2010 as well as some documention on how XBMC is working? Maybe I can help in porting something, but knowledge of C/C++ is limited. Hovever I can help with porting skins to XBMC-360, I've got some experience with skinning while I was creating my streamin app for OG Xbox.

Happy coding!

**Comment by wolfysdl** [comment]
> I'm opening this issue for general discussion about XBMC-360 development. These issue is meant for developers and not for general help :) So I will start with my questions.
> 
> 1. **Skinning engine / GUILIB** - If I understand correctly your main task is to finish all GUI controls so skins from XBMC4Xbox can be used. That will make them compatible with XBMC-360 out-of-the box, am I right? I've build app from Development branch, but I couldn't get focus on control, even though I set inside `<defaultcontrol></defaultcontrol>` number "4" which was ID of my button control that activates Settings window (Settings.xml). So I was wondering is that some bug? Maybe better options would be to first port whole GUILIB from XBMC4Xbox and after that start adding new features from Kodi.
> 2. **Video playback / DVDPlayer/FFMpeg** - I've tried a lof of different video files and general rule is that 720p/H.263 (know as DiVX and XviD) are playing very well, but video quality of this videos is bad at bigger screens. Also Original Xbox is also capable of playing this videos so there is no suprise they work on 360. But 720p/1080p H.264 (known as WEB-DL, YTS, YIFY and similar releases) are no way to go for 360. 1080p H.264 wont even start, and 720p H.264 are stuttering as hell (unwachable, frame skipping, 10-12FPS). Taking in considiration how much power 360 has against Original Xbox it would be really a shame if we can't get working at least 1080p H.264/265 video files. I don't know is this something related to old version of FFmpeg but I hope that there is fix for this.
> 3. Is there any official docs that explains how to debbug with 360 inside VS2010 as well as some documention on how XBMC is working? Maybe I can help in porting something, but knowledge of C/C++ is limited. Hovever I can help with porting skins to XBMC-360, I've got some experience with skinning while I was creating my streamin app for OG Xbox.
> 
> Happy coding!

Hi there,
first: Yes we´re focusing on the port of the GUIControl group since he is asked for me to do it, to upgrade the gui and some stuff however the functionality is not 100% effective even for me and marty with his ``Developemt`` branch. 
Second: Yes, it is true that the videos are not working i suggest to see my channel for see my [video](https://www.youtube.com/channel/UCzMnDI1qhD6egKLMTezysxg) about this, the majority of the codecs is not really working unless some exceptions, only avi(divx or xvid) i´m working heavily on update the old FFMpeg to FFMpeg 5.1.1 'Lorrentz' to work i even updated the zlib to 1.2.15 and pthreads to 3.8.0 and now i´m planning to support tinyxml2 soon but, i can talk this about this later, you can check out my [branch](https://github.com/wolfysdl/XBMC-360/tree/ffmpeg-update) to see about it 
Third: sorry i can´t respond this question, i will leave to him to respond this one. 
since this repo is not mine and i´m just freelly help him since he doesn´t have time to really dedicate to this project.

**Comment by antonic901** [comment]
> > I'm opening this issue for general discussion about XBMC-360 development. These issue is meant for developers and not for general help :) So I will start with my questions.
> > 
> > 1. **Skinning engine / GUILIB** - If I understand correctly your main task is to finish all GUI controls so skins from XBMC4Xbox can be used. That will make them compatible with XBMC-360 out-of-the box, am I right? I've build app from Development branch, but I couldn't get focus on control, even though I set inside `<defaultcontrol></defaultcontrol>` number "4" which was ID of my button control that activates Settings window (Settings.xml). So I was wondering is that some bug? Maybe better options would be to first port whole GUILIB from XBMC4Xbox and after that start adding new features from Kodi.
> > 2. **Video playback / DVDPlayer/FFMpeg** - I've tried a lof of different video files and general rule is that 720p/H.263 (know as DiVX and XviD) are playing very well, but video quality of this videos is bad at bigger screens. Also Original Xbox is also capable of playing this videos so there is no suprise they work on 360. But 720p/1080p H.264 (known as WEB-DL, YTS, YIFY and similar releases) are no way to go for 360. 1080p H.264 wont even start, and 720p H.264 are stuttering as hell (unwachable, frame skipping, 10-12FPS). Taking in considiration how much power 360 has against Original Xbox it would be really a shame if we can't get working at least 1080p H.264/265 video files. I don't know is this something related to old version of FFmpeg but I hope that there is fix for this.
> > 3. Is there any official docs that explains how to debbug with 360 inside VS2010 as well as some documention on how XBMC is working? Maybe I can help in porting something, but knowledge of C/C++ is limited. Hovever I can help with porting skins to XBMC-360, I've got some experience with skinning while I was creating my streamin app for OG Xbox.
> > 
> > Happy coding!
> 
> Hi there, first: Yes we´re focusing on the port of the GUIControl group since he is asked for me to do it, to upgrade the gui and some stuff however the functionality is not 100% effective even for me and marty with his `Developemt` branch. Second: Yes, it is true that the videos are not working i suggest to see my channel for see my [video](https://www.youtube.com/watch?v=S5wC7hWulvg&t=37s) about this, the majority of the codecs is not really working unless some exceptions, only avi(divx or xvid) i´m working heavily on update the old FFMpeg to FFMpeg 5.1.1 'Lorrentz' to work i even updated the zlib to 1.2.12 and pthreads to 3.0.0 and now i´m planning to support tinyxml2 soon but, i probablly can talk this about this later, you can check out my [branch](https://github.com/wolfysdl/XBMC-360/tree/ffmpeg-update) to see about it Third: sorry i can´t respond this question, i will leave to him to respond this one. since this repo is not mine and i´m just freelly help him since he doesn´t have time to really dedicate to this project.

Thanks for quick answer. I hope you two will manage to port newer version of FFMpeg so 1080p H.264/265 videos can be played smoothly on 360. I'm currently busy, but I will take a closer look on XBMC4Xbox and Kodi source code, maybe I can do something to help. Hovever, when it comes to plugins and scripts porting and creating Skins, I can help with that. But I need green light from main developer when GUILIB is updated so I can start porting of Confluence Lite skin. I don't want to create some skin, and in the next update that skin wouldn't work because of GUILIB update.


One more question for you. Do you maybe know how hard would it be to port some features from Kodi GUILIB in XBMC4Xbox? That will make porting of Kodi skins, like Estuary skin a much easier task. I've tried to port Estuary skin, but then I quick realised that it would be much easier to just write skin from scratch.

**Comment by wolfysdl** [comment]
> > > I'm opening this issue for general discussion about XBMC-360 development. These issue is meant for developers and not for general help :) So I will start with my questions.
> > > 
> > > 1. **Skinning engine / GUILIB** - If I understand correctly your main task is to finish all GUI controls so skins from XBMC4Xbox can be used. That will make them compatible with XBMC-360 out-of-the box, am I right? I've build app from Development branch, but I couldn't get focus on control, even though I set inside `<defaultcontrol></defaultcontrol>` number "4" which was ID of my button control that activates Settings window (Settings.xml). So I was wondering is that some bug? Maybe better options would be to first port whole GUILIB from XBMC4Xbox and after that start adding new features from Kodi.
> > > 2. **Video playback / DVDPlayer/FFMpeg** - I've tried a lof of different video files and general rule is that 720p/H.263 (know as DiVX and XviD) are playing very well, but video quality of this videos is bad at bigger screens. Also Original Xbox is also capable of playing this videos so there is no suprise they work on 360. But 720p/1080p H.264 (known as WEB-DL, YTS, YIFY and similar releases) are no way to go for 360. 1080p H.264 wont even start, and 720p H.264 are stuttering as hell (unwachable, frame skipping, 10-12FPS). Taking in considiration how much power 360 has against Original Xbox it would be really a shame if we can't get working at least 1080p H.264/265 video files. I don't know is this something related to old version of FFmpeg but I hope that there is fix for this.
> > > 3. Is there any official docs that explains how to debbug with 360 inside VS2010 as well as some documention on how XBMC is working? Maybe I can help in porting something, but knowledge of C/C++ is limited. Hovever I can help with porting skins to XBMC-360, I've got some experience with skinning while I was creating my streamin app for OG Xbox.
> > > 
> > > Happy coding!
> > 
> > 
> > Hi there, first: Yes we´re focusing on the port of the GUIControl group since he is asked for me to do it, to upgrade the gui and some stuff however the functionality is not 100% effective even for me and marty with his `Developemt` branch. Second: Yes, it is true that the videos are not working i suggest to see my channel for see my [video](https://www.youtube.com/watch?v=S5wC7hWulvg&t=37s) about this, the majority of the codecs is not really working unless some exceptions, only avi(divx or xvid) i´m working heavily on update the old FFMpeg to FFMpeg 5.1.1 'Lorrentz' to work i even updated the zlib to 1.2.12 and pthreads to 3.0.0 and now i´m planning to support tinyxml2 soon but, i probablly can talk this about this later, you can check out my [branch](https://github.com/wolfysdl/XBMC-360/tree/ffmpeg-update) to see about it Third: sorry i can´t respond this question, i will leave to him to respond this one. since this repo is not mine and i´m just freelly help him since he doesn´t have time to really dedicate to this project.
> 
> Thanks for quick answer. I hope you two will manage to port newer version of FFMpeg so 1080p H.264/265 videos can be played smoothly on 360. I'm currently busy, but I will take a closer look on XBMC4Xbox and Kodi source code, maybe I can do something to help. Hovever, when it comes to plugins and scripts porting and creating Skins, I can help with that. But I need green light from main developer when GUILIB is updated so I can start porting of Confluence Lite skin. I don't want to create some skin, and in the next update that skin wouldn't work because of GUILIB update.
> 
> One more question for you. Do you maybe know how hard would it be to port some features from Kodi GUILIB in XBMC4Xbox? That will make porting of Kodi skins, like Estuary skin a much easier task. I've tried to port Estuary skin, but then I quick realised that it would be much easier to just write skin from scratch.

Well this one i think the source of XBMC-360 or XBMC4XBOX should be updated for the latest branch of the kodi itself however it would be insane pain because the code that XBNC4XBOX uses is outdated so i don't know if me or marty, will work on this

**Comment by antonic901** [comment]
Well, if we could get only GUILIB from Kodi krypton, that would be awesome. We maybe don't need whole port of GUILIB but only some cruital things like [params in include](https://kodi.wiki/view/Skinning_Manual#Use_params_in_includes), [colordiffuse attribute for textures](https://redmine.exotica.org.uk/issues/357) etc. This things would make porting of Kodi skins a much easier task

**Comment by wolfysdl** [comment]
> Well, if we could get only GUILIB from Kodi krypton, that would be awesome. We maybe don't need whole port of GUILIB but only some cruital things like [params in include](https://kodi.wiki/view/Skinning_Manual#Use_params_in_includes), [colordiffuse attribute for textures](https://redmine.exotica.org.uk/issues/357) etc. This things would make porting of Kodi skins a much easier task

The coldfuse is easy atleast

**Comment by antonic901** [comment]
When I get time I will try to port part by part GUILIB from Krypton branch of Kodi. I have zero experience in advanced C/C++ programming but nothing is stopping me to try and learn something new. But when you two get GUILIB ported from XBMC4Xbox and if there was need of some skin porting feel fre to contact me. I've also have plans to port my scripts and plugins to XBMC-360.

**Comment by wolfysdl** [comment]
> When I get time I will try to port part by part GUILIB from Krypton branch of Kodi. I have zero experience in advanced C/C++ programming but nothing is stopping me to try and learn something new. But when you two get GUILIB ported from XBMC4Xbox and if there was need of some skin porting feel fre to contact me. I've also have plans to port my scripts and plugins to XBMC-360.

Ok, i will contact as soon if this at least is working properly now i´m planning to port some classes of password, profile and folder manager here is a image
![Screenshot_4](https://user-images.githubusercontent.com/75867486/192389339-20d8403a-f5e7-4aae-9d85-bb40ee5cb509.png)

**Comment by antonic901** [comment]
I will maybe try to port Weather Window because I have worked on XBMC4Xbox weather part and I'm somehow familiar with it. Are there any differences on how messages are working compared to XMBC4Xbox?

And one curiosity question. How far you are from complete GUILIB port? I was thinking to start creating new skins (maybe skin based on Aurora or Blades dash) but I don't know is it right time for that. If there are goin to be some big changes maybe the best option would be to wait..
